export const AUTH_LITERALS = {
  ADMIN: {
    LOGIN_TITLE: 'Sign in',
    LOGIN_SUBTITLE: 'Use your work email to continue.',
    FORGOT_PASSWORD_TITLE: 'Forgot your password?',
    FORGOT_PASSWORD_SUBTITLE: "Enter your work email and we'll send you a link to reset it. The link works for 1 hour.",
    RESET_PASSWORD_TITLE: 'Set a new password',
    RESET_PASSWORD_SUBTITLE: 'Use at least 8 characters. You will be signed out on other devices.',
    CHANGE_PASSWORD_TITLE: 'Change Password',
    EMAIL_LABEL: 'Work email',
    PASSWORD_LABEL: 'Password',
    SUBMIT_LOGIN: 'Sign in',
    SUBMIT_FORGOT: 'Send reset link',
    SUBMIT_RESET: 'Update password',
    FORGOT_LINK: 'Forgot password?',
    BACK_TO_LOGIN: 'Back to sign in',
  },
  USER: {
    LOGIN_TITLE: 'Sign in',
    LOGIN_SUBTITLE: 'Use your work email to continue.',
    FORGOT_PASSWORD_TITLE: 'Forgot your password?',
    FORGOT_PASSWORD_SUBTITLE: "Enter your work email. We'll send a reset link that works for 1 hour.",
    RESET_PASSWORD_TITLE: 'Set a new password',
    RESET_PASSWORD_SUBTITLE: 'Use at least 8 characters.',
    EMAIL_LABEL: 'Work email',
    PASSWORD_LABEL: 'Password',
    SUBMIT_LOGIN: 'Sign in',
    SUBMIT_FORGOT: 'Send reset link',
    SUBMIT_RESET: 'Update password',
    FORGOT_LINK: 'Forgot?',
    BACK_TO_LOGIN: 'Back to sign in',
  },
} as const;
