export const AUTH_LITERALS = {
  ADMIN: {
    LOGIN_TITLE: 'Admin Sign In',
    LOGIN_SUBTITLE: 'Access the management portal',
    FORGOT_PASSWORD_TITLE: 'Reset Admin Password',
    FORGOT_PASSWORD_SUBTITLE: 'Enter your admin email to receive reset instructions',
    RESET_PASSWORD_TITLE: 'Set New Admin Password',
    RESET_PASSWORD_SUBTITLE: 'Choose a strong password for your admin account',
    CHANGE_PASSWORD_TITLE: 'Change Password',
    EMAIL_LABEL: 'Admin Email',
    PASSWORD_LABEL: 'Password',
    SUBMIT_LOGIN: 'Sign In',
    SUBMIT_FORGOT: 'Send Reset Link',
    SUBMIT_RESET: 'Reset Password',
    FORGOT_LINK: 'Forgot password?',
    BACK_TO_LOGIN: 'Back to sign in',
  },
  USER: {
    LOGIN_TITLE: 'Employee Sign In',
    LOGIN_SUBTITLE: 'Access your employee portal',
    FORGOT_PASSWORD_TITLE: 'Reset Password',
    FORGOT_PASSWORD_SUBTITLE: 'Enter your work email to receive reset instructions',
    RESET_PASSWORD_TITLE: 'Set New Password',
    RESET_PASSWORD_SUBTITLE: 'Choose a strong password for your employee account',
    EMAIL_LABEL: 'Work email',
    PASSWORD_LABEL: 'Password',
    SUBMIT_LOGIN: 'Sign In',
    SUBMIT_FORGOT: 'Send Reset Link',
    SUBMIT_RESET: 'Reset Password',
    FORGOT_LINK: 'Forgot password?',
    BACK_TO_LOGIN: 'Back to sign in',
  },
} as const;
